version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.4
    working_directory: ~/codeclimate/codeclimate-services
    steps:
      - checkout
      - run: bundle install && bundle exec rake && bundle exec codeclimate-test-reporter

workflows:
  version: 2
  test:
    jobs:
      - test
